export const mockProjects = [
  {
    id: '1',
    name: 'Website Redesign',
    description: 'Complete overhaul of the company website',
    status: 'In Progress',
    dueDate: '2026-03-15',
    avatarColors: ['#3B82F6', '#10B981'],
    avatarNames: ['JD', 'SM'],
  },
  {
    id: '2',
    name: 'Mobile App Development',
    description: 'iOS and Android application',
    status: 'Todo',
    dueDate: '2026-04-01',
    avatarColors: ['#F59E0B', '#EF4444', '#8B5CF6'],
    avatarNames: ['AK', 'BP', 'CW'],
  },
  {
    id: '3',
    name: 'API Integration',
    description: 'Third-party service integration',
    status: 'Done',
    dueDate: '2026-02-28',
    avatarColors: ['#06B6D4'],
    avatarNames: ['RT'],
  },
  {
    id: '4',
    name: 'Dashboard Analytics',
    description: 'Real-time analytics dashboard',
    status: 'In Progress',
    dueDate: '2026-03-20',
    avatarColors: ['#EC4899', '#14B8A6'],
    avatarNames: ['ML', 'NK'],
  },
  {
    id: '5',
    name: 'Email Campaign',
    description: 'Marketing email automation',
    status: 'Todo',
    dueDate: '2026-03-25',
    avatarColors: ['#F97316'],
    avatarNames: ['DG'],
  },
]

export const initialColumns = [
  { id: 'todo', title: 'To Do', color: '#6B7280' },
  { id: 'inprogress', title: 'In Progress', color: '#3B82F6' },
  { id: 'done', title: 'Done', color: '#10B981' },
]

export const initialTasks = [
  {
    id: 't1',
    columnId: 'todo',
    title: 'Design mockups',
    description: 'Create initial wireframes',
    startDate: '2026-03-02',
    dueDate: '2026-03-10',
    avatarColors: ['#3B82F6'],
    avatarNames: ['JD'],
  },
  {
    id: 't2',
    columnId: 'todo',
    title: 'Setup project structure',
    description: 'Initialize repository',
    startDate: '2026-03-01',
    dueDate: '2026-03-08',
    avatarColors: ['#10B981'],
    avatarNames: ['SM'],
  },
  {
    id: 't3',
    columnId: 'inprogress',
    title: 'Implement authentication',
    description: 'Add OAuth2 support',
    startDate: '2026-03-04',
    dueDate: '2026-03-12',
    avatarColors: ['#F59E0B'],
    avatarNames: ['AK'],
  },
  {
    id: 't4',
    columnId: 'inprogress',
    title: 'Database schema design',
    description: 'Design tables and relationships',
    startDate: '2026-03-03',
    dueDate: '2026-03-09',
    avatarColors: ['#EF4444'],
    avatarNames: ['BP'],
  },
  {
    id: 't5',
    columnId: 'done',
    title: 'Initial planning',
    description: 'Project kickoff meeting',
    startDate: '2026-02-24',
    dueDate: '2026-03-01',
    avatarColors: ['#8B5CF6'],
    avatarNames: ['CW'],
  },
  {
    id: 't6',
    columnId: 'done',
    title: 'Requirements gathering',
    description: 'Document all features',
    startDate: '2026-02-26',
    dueDate: '2026-03-03',
    avatarColors: ['#EC4899'],
    avatarNames: ['ML'],
  },
]
